import { createApp } from "vue";
import { createPinia } from "pinia";
import App from "@/App.vue";
import router from "@/router";
import "@/assets/css/tailwind-base.css";
import "@/assets/css/tailwind-utilities.css";
import "@/assets/css/tailwind-components.css";
import "@/assets/css/animation.css";
import "@/assets/css/master.css";
const pinia = createPinia();
createApp(App).use(router).use(pinia).mount("#app");
